### ISSUE TITLE
Why do you re-organize issues?

### ISSUE THREAD

**Issue by ArjixWasTaken** [inson1/inson1#1]
Like, really why?

**Comment by ArjixWasTaken** [comment]
What does it even mean to re-organize an issue?
Do you sort your issues by recently active or smth?

Is it important for you to have them sorted?

**Comment by inson1** [comment]
@ArjixWasTaken you can search your issues, that not include some phrase - I add it to what I feel is done or I dont care anymore

sorry if you got notification or something, because of that

**Comment by ArjixWasTaken** [comment]
Well, couldn't you just edit an existing message to have that phrase?

**Comment by inson1** [comment]
@ArjixWasTaken yea I could do that and maybe it would be better
